name: flutter_firestore_visual_query
description: A visual way to query your firestore database for testing using Flutter
version: 0.0.2
author: Jonathan White <jwhite@thinkdigital.software>
homepage: https://github.com/ThinkDigitalRepair/flutter_firestore_visual_query

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.11.0+1
  flutter_bloc: ^0.13.0
  bloc: ^0.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

