name: flutter_firestore_visual_query
description: A visual way to query your firestore database for testing using Flutter
version: 0.1.0
author: Jonathan White <jwhite@thinkdigital.software>
homepage: https://github.com/ThinkDigitalRepair/flutter_firestore_visual_query

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.9+5
  flutter_bloc: ^0.22.1
  bloc: ^0.16.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

